
[libraries]
spring-web = { module = "org.springframework:spring-web"}
spring-boot = { module = "org.springframework.boot:spring-boot-starter-web"}
spring-kafka = { module = "org.springframework.kafka:spring-kafka"}
cloud-ver = { module = "'org.springframework.cloud:spring-cloud-dependencies'", version = "2021.0.3"}
spring-fegin = { module = "org.springframework.cloud:spring-cloud-starter-openfeign"}
spring-test = { module = "org.springframework.boot:spring-boot-starter-test" }
spring-security = { module = "org.springframework.boot:spring-boot-starter-security" }
spring-feign = { module = "org.springframework.cloud:spring-cloud-starter-openfeign" }
java-validation = { module = "javax.validation:validation-api", version = "2.0.1.Final" }
jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
hibernate = { module = "org.hibernate:hibernate-core", version = "6.2.5.Final" }
lombok = { module = "org.projectlombok:lombok", version = "1.18.30" }
sl4j = { module = "org.slf4j:slf4j-api", version = "1.7.30" }
h2 = { module = "com.h2database:h2", version = "2.1.214" }
mysql = { module = "mysql:mysql-connector-java", version = "8.0.13" }
json = { module = "com.fasterxml.jackson.core:jackson-annotations", version = "2.15.2" }
jwt ={module ="io.jsonwebtoken:jjwt",version ="0.9.1"}
spring-oauth = { module = "org.springframework.security:spring-security-oauth2-client" }
spring-redis = { module = "org.springframework.data:spring-data-redis" }
redis-client = { module = "redis.clients:jedis", version ="3.10.0"}
apache-avro = { module = "org.apache.avro:avro", version = "1.8.2" }

